import { MOCK_VIDEOS, makeId } from './utils.js';
const VIDEO_KEY = 'videovault_videos'; const COLLECTION_KEY = 'videovault_collections';
const hasChromeStorage = typeof chrome !== 'undefined' && chrome.storage?.local;
async function read(key, fallback) { if (hasChromeStorage) return (await chrome.storage.local.get(key))[key] ?? fallback; return JSON.parse(localStorage.getItem(key) || 'null') ?? fallback; }
async function write(key, value) { if (hasChromeStorage) return chrome.storage.local.set({ [key]: value }); localStorage.setItem(key, JSON.stringify(value)); }
function normalizeVideo(video) { return { id: video.id || makeId(), title: video.title || '', description: video.description || '', url: video.url || '', canonicalUrl: video.canonicalUrl || video.url || '', pageUrl: video.pageUrl || video.url || '', platform: video.platform || 'Other', domain: video.domain || '', videoId: video.videoId || '', creator: video.creator || { name: '', username: '', profileUrl: '' }, video: video.video || { duration: video.duration ?? null, width: null, height: null, aspectRatio: null, format: '', mimeType: '', quality: '', frameRate: null, bitrate: null }, thumbnail: video.thumbnailData || (typeof video.thumbnail === 'object' ? video.thumbnail : { url: video.thumbnail || '', width: null, height: null, format: '', quality: '', source: '', alternatives: [] }), engagement: video.engagement || { views: null, likes: null, comments: null, shares: null }, publication: video.publication || { publishedAt: null }, tags: video.tags || [], hashtags: video.hashtags || [], categories: video.categories || [], savedAt: video.savedAt || new Date().toISOString(), updatedAt: video.updatedAt || new Date().toISOString(), favorite: Boolean(video.favorite), collections: video.collections || [], metadata: video.metadata || { extractionMethod: [], extractionSuccess: true } }; }
export async function getVideos() { const videos = await read(VIDEO_KEY, null); if (videos) return videos.map(normalizeVideo); await write(VIDEO_KEY, MOCK_VIDEOS); return MOCK_VIDEOS.map(normalizeVideo); }
export async function findDuplicate(video) { const videos = await getVideos(); const keys = [video.canonicalUrl, video.url, video.videoId && `${video.platform}:${video.videoId}`].filter(Boolean); return videos.find(item => keys.includes(item.canonicalUrl) || keys.includes(item.url) || (video.videoId && item.videoId === video.videoId && item.platform === video.platform)); }
export async function saveVideo(video) { const videos = await getVideos(); const now = new Date().toISOString(); const saved = normalizeVideo({ ...video, id: makeId(), savedAt: now, updatedAt: now }); await write(VIDEO_KEY, [saved, ...videos]); return saved; }
export async function updateVideo(id, updates) { const videos = await getVideos(); const updated = videos.map(video => video.id === id ? { ...video, ...updates } : video); await write(VIDEO_KEY, updated); return updated.find(video => video.id === id); }
export async function deleteVideo(id) { const videos = await getVideos(); await write(VIDEO_KEY, videos.filter(video => video.id !== id)); }
export async function toggleFavorite(id) { const videos = await getVideos(); const video = videos.find(item => item.id === id); return updateVideo(id, { favorite: !video.favorite }); }
export async function getCollections() { return read(COLLECTION_KEY, ['Java', 'Angular', 'Trading', 'Tutorials', 'Entertainment', 'Music']); }
export async function createCollection(name) { const collections = await getCollections(); if (!collections.includes(name)) await write(COLLECTION_KEY, [...collections, name]); }
export async function deleteCollection(name) { const collections = await getCollections(); await write(COLLECTION_KEY, collections.filter(collection => collection !== name)); }